### ISSUE TITLE
Ticket cannot be tested using fake clockwork

### ISSUE THREAD

**Issue by Season0518** [jonboulle/clockwork#79]
I wrote a simple function that executes a certain piece of code at a specified interval.

``` go
func ScheduledTask(c clockwork.Clock) {
	ticker := c.NewTicker(1 * time.Hour)
	go func() {
		defer ticker.Stop()

		for range ticker.Chan() {
			fmt.Printf("responsed\n")
		}
	}()
}
```

I referred to the Readme and wrote a unit test like this.

``` go
func TestScheduledTask(t *testing.T) {
	fakeClock := clockwork.NewFakeClock()

	var wg sync.WaitGroup
	wg.Add(1)

	go func() {
		ScheduledTask(fakeClock)
		wg.Done()
	}()
	fakeClock.BlockUntil(1)
	for i := 0; i < 24; i++ {
		fakeClock.Advance(1*time.Hour + 1*time.Second)
		//time.Sleep(1 * time.Millisecond)
	}
	wg.Wait()
}
```

The program cannot produce the expected output.

``` sh
=== RUN   TestScheduledTask
--- PASS: TestScheduledTask (0.00s)
PASS
```

But when I set a delay of one millisecond for each loop, the output of the program is as follows

``` sh
=== RUN   TestScheduledTask
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
responsed
--- PASS: TestScheduledTask (0.03s)
PASS
```

Is this a bug or a usage issue?

**Comment by DPJacques** [comment]
This is not a bug. It is caused by a race condition caused by the goroutine created in ScheduledTask.

Without the time.Sleep, your program exits before the goroutine created in ScheduledTask is able to start. There are a number of different ways you can address this, but I'd need to know more about what you are trying to accomplish. I would probably use a channel to validate the goroutine created in ScheduledTask is running before I enter the for loop.
